// Import necessary modules from Redux Toolkit

import { createSlice } from "@reduxjs/toolkit";

// Define initial state for the authentication slice
const initialState = {
  userInfo: localStorage.getItem("userInfo") ? JSON.parse(localStorage.getItem("userInfo")) : null
};

// Create the authSlice using createSlice function
const authSlice = createSlice({
  name: "auth", // Name of the slice
  initialState, // Initial state for the slice
  reducers: {
    // Reducer function to set user credentials in state and localStorage
    setCredentials: (state, action) => {
      state.userInfo = action.payload; // Update userInfo in state with payload
      localStorage.setItem("userInfo", JSON.stringify(action.payload)); // Update userInfo in localStorage
    },
    // Reducer function to logout user by clearing userInfo from state and localStorage
    logout: (state, action) => {
      state.userInfo = null; // Clear userInfo in state
      localStorage.removeItem("userInfo"); // Remove userInfo from localStorage
    },
   
  }
});

// Extract action creators from authSlice.actions
export const { setCredentials, logout } = authSlice.actions;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
