/* global builder */

// Importing constants for API endpoints

import { ORDER_URL } from "../constant";
import { apiSlice } from "./apiSlice";

// Creating an orderApiSlice using the injectEndpoints function from apiSlice
const orderApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Configuration for creating an order
    createOrder: builder.mutation({
      query: (order) => ({
        url: ORDER_URL,
        method: "POST",
        body: { ...order }
      })
    })
  })
});

// Exporting specific hooks generated by orderApiSlice for use in components
export const { useCreateOrderMutation } = orderApiSlice;
